workspace:
   base: /drone
   path: src/github.com/vaibhavk9/godrone

pipeline:

  build:
    image: golang:1.8
    commands:
      - go build                
      
      
  gcr:
    image: stayfari/drone-gcr
    registry: gcr.io/zang-api-sandbox
    repo: gcr.io/zang-api-sandbox/godrone
    storage_driver: overlay
    privileged: true
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    token: ${docker_password}
    
