workspace:
  base: /go
  path: src/github.com/vaibhavk9/godrone

pipeline:

  test:
    image: golang:1.8
    commands:
      - go get github.com/vaibhavk9/godrone
      - go test github.com/vaibhavk9/godrone

  build:
    image: golang:1.8
    commands:
      - go build                 
