
pipeline:
      
  build:
    image: golang:1.8
    commands:
      - echo ${GIT_USER} && echo $$GIT_PASS
      - cd /root && echo "machine github.com" >> .netrc && echo "login $GIT_USER" >> .netrc && echo "password $GIT_PASS" >> .netrc
      - cat .netrc
      - cd -
      - go get 
      - go build
      
                  
            
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/godrone
    privileged: true
    secrets: [ docker_username, docker_password ]
    debug: true


