workspace:
   base: /drone
   path: src/github.com/vaibhavk9/godrone

pipeline:

  build:
    image: golang:1.8
    commands:
      - go build                
      
      
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/vaibhavk9/godrone
    privileged: true
    secrets: [ docker_username, docker_password ]
    debug: true  
    tag: "1.0"


  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: cloud-commits
    username: Drone
    template: >
     {{#success build.status}}
       Build {{build.number}} for {{repo.owner}}/{{repo.name}} succeeded. Build Link : {{build.link}}
     {{else}}
       Build {{build.number}} failed. 
     {{/success}}
