pipeline:
  
  build:
    image: golang:1.7
    pull: true
    commands:
      - go get -u github.com/vaibhavk9/godrone
      - go test -cover -coverprofile coverage.out
      - go build

  publish:
  coverage:
    when:
    branch: master
