workspace:
   base: /drone
   path: src/github.com/vaibhavk9/godrone

pipeline:

  build:
    image: golang:1.8
    commands:
      - go build                
      
      
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/godrone
    username: _json_key
    password: [ docker_password ]
    debug: true
    insecure: true
