
pipeline:
      
  build:
    image: golang:1.8
    auth_config:
      username: vaibhavk9
      password: vkspace9
      email: vaibhav_space@hotmail.com
    commands:
      - go get
      - go build                
      
      
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/godrone
    privileged: true
    secrets: [ docker_username, docker_password ]
    debug: true
