
pipeline:
      
  build:
    image: golang:1.8
    commands:
      - pwd && ls -la
      - cd /drone/src/github.com && ls -al
      
                  
            
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/godrone
    privileged: true
    secrets: [ docker_username, docker_password ]
    debug: true

