
pipeline:
      
  build:
    image: golang:1.8
    commands:
      - cat /root/.netrc
      - git config --global user.email "vaibhav_space@hotmail.com"
      - git config --global user.name "vaibhavk9"
      - go get ./...
      - go build                
      
      
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/godrone
    privileged: true
    secrets: [ docker_username, docker_password ]
    debug: true
