workspace:
  base: /go
  path: src/github.com/vaibhavk9/godrone

build:
    image: golang:1.7
    commands:
      - go get -u github.com/vaibhavk9/godrone
      - go test -cover -coverprofile coverage.out
      - go build github.com/vaibhavk9/godrone
      
publish:
  coverage:
    when:
    branch: master      
