workspace:
   base: /go
   path: src/github.com/vaibhavk9/godrone
   
pipeline:
      
  build:
    image: golang
    secrets: [ git_user, git_pass ]
     
    commands:
      - cd /root && echo "machine github.com" >> .netrc && echo "login $GIT_USER" >> .netrc && echo "password $GIT_PASS" >> .netrc
      - cd -
      - go get ./... 
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install
      - cp /go/bin/* /go/src/github.com/vaibhavk9/godrone/
            
                  
            
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/godrone
    privileged: true
    secrets: [ docker_username, docker_password ]
    debug: true
    tag: "2.0"
