workspace:
  base: /go
  path: src/github.com/vaibhavk9/godrone

pipeline:

  build:
    image: golang:1.8
    commands:
      - go build github.com/vaibhavk9/godrone                
  
  docker:
    image: plugins/docker
    insecure: true
    username: vaibhavk9
    password: Vkspace@99
    email: vaibhav_space@hotmail.com
    repo:     vaibhavk9/godrone
    tag:      latest
    file:     Dockerfile   
