workspace:
  base: /go
  path: src/github.com/vaibhavk9/godrone

build:
    image: golang:1.7
    commands:
      - go test -cover -coverprofile coverage.out
            
publish:
  coverage:
    when:
    branch: master      
