workspace:
  base: /go
  path: src/github.com/vaibhavk9/godrone

pipeline:

  build:
    image: golang:1.8
    commands:
      - go build github.com/vaibhavk9/godrone                
  
  gcr:
    image: plugins/gcr
    environment:
      		- DOCKER_LAUNCH_DEBUG=true
    repo: vaibhavk9/godrone
    token: >
      $$GCR_TOKEN
