
pipeline:
      
  build:
    image: golang:1.8
    commands:
      - cd /root && echo "machine github.com" >> .netrc && echo "login $USER" >> .netrc && echo "password $PASS" >> .netrc
      - ls -la
      - cd -
      - go get 
      - go build
      
                  
            
  gcr:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/zang-api-sandbox/godrone
    privileged: true
    secrets: [ docker_username, docker_password ]
    debug: true


