workspace:
    base: /go
    path: src/github.com/vaibhavk9/godrone
  
pipeline:
  test:
    mage: golang:1.7
    pull: true
    commands:
      - go get -u github.com/vaibhavk9/godrone
      - go test github.com/vaibhavk9/godrone
  
  build:
    image: golang:1.7
    pull: true
    commands:
      - go get -u github.com/vaibhavk9/godrone
      - go build
