workspace:
   base: /go
   path: src/github.com/vaibhavk9/godrone

pipeline:

  build:
    image: golang:1.8
    commands:
      - go build github.com/vaibhavk9/godrone                
  
  publish:
    image: stayfari/drone-gcr
    repo: vaibhavk9/godrone
    storage_driver: overlay
    privileged: true
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    token: >$$GCR_TOKEN  
