workspace:
  base: /go
  path: src/github.com/vaibhavk9/godrone

pipeline:

  test:
    image: golang:1.8
    commands:
      - go get -u github.com/vaibhavk9/godrone
      - go test -u github.com/vaibhavk9/godrone

  build:
    image: golang:1.8
    commands:
      - go get 
      - go build
                  
